# Generated by Django 3.0.5 on 2020-04-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('icon', models.ImageField(help_text='图标', upload_to='medical/category/', verbose_name='图标')),
            ],
            options={
                'verbose_name': '类目',
                'verbose_name_plural': '类目',
                'db_table': 'medicine_category',
            },
        ),
    ]
