# Generated by Django 3.0.5 on 2020-04-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='medicine_nums',
            field=models.IntegerField(default=0, verbose_name='类别下的药品数量'),
        ),
    ]
