# Generated by Django 3.0.5 on 2020-05-24 16:34

from django.db import migrations, models
import medical.medicine.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20200419_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(help_text='图标', upload_to=medical.medicine.models.upload_to_category, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(upload_to=medical.medicine.models.upload_to_medicine, verbose_name='商品图片'),
        ),
    ]
