# Generated by Django 3.0.5 on 2020-05-27 21:48

import ckeditor_uploader.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('medicine', '0004_auto_20200524_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='sold_num',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='symptom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='病症'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='药品说明书'),
        ),
    ]
