# Generated by Django 3.0.5 on 2020-05-27 22:05

from django.db import migrations, models
import medical.medicine.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_auto_20200527_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, upload_to=medical.medicine.models.upload_to_medicine, verbose_name='商品图片'),
        ),
    ]
