# Generated by Django 3.0.5 on 2020-04-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学院'),
        ),
        migrations.AddField(
            model_name='user',
            name='clazz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='user',
            name='dormitory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='宿舍'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, '学生'), (1, '医务人员')], default=0, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
    ]
