# Generated by Django 3.0.5 on 2020-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='校医室名称')),
                ('lat', models.FloatField(default=0.0, verbose_name='纬度')),
                ('lng', models.FloatField(default=0.0, verbose_name='经度')),
                ('open_time', models.TimeField(verbose_name='开门时间')),
                ('close_time', models.TimeField(verbose_name='关门时间')),
                ('description', models.TextField(verbose_name='医务室介绍')),
                ('is_open', models.IntegerField(default=1, verbose_name='是否开门')),
            ],
            options={
                'verbose_name': '医务室信息',
                'verbose_name_plural': '医务室信息',
            },
        ),
    ]
