# Generated by Django 3.0.5 on 2020-05-23 14:37

from django.db import migrations, models
import medical.article.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=medical.article.models.upload_main_image, verbose_name='主图'),
        ),
    ]
